# Generated by Django 5.0.4 on 2024-05-12 10:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['id']},
        ),
        migrations.AddIndex(
            model_name='cart',
            index=models.Index(fields=['id'], name='products_ca_id_85ede4_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['id'], name='products_ca_id_805265_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['id'], name='products_co_id_74a227_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['id'], name='products_pr_id_b46934_idx'),
        ),
    ]
