# Generated by Django 5.0.4 on 2024-05-12 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_cart_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='national',
            field=models.BooleanField(default=True),
        ),
    ]
