# Generated by Django 5.0.4 on 2024-05-12 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_category_national'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='order_users_count',
            field=models.IntegerField(default=0),
        ),
    ]
