# Generated by Django 5.0.4 on 2024-05-12 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_rename_order_users_count_category_products_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='popular_products',
            field=models.IntegerField(default=0),
        ),
    ]
